### ISSUE TITLE
Suggestion: tag repository with "mcnp" topic

### ISSUE THREAD

**Issue by MicahGale** [lanl/mcnptools#7]
There is a growing topic [mcnp](https://github.com/topics/mcnp) on github. I think linking this library to that topic will make it more discoverable, and very helpful, as this is one of the most helpful Open Source projects for MCNP. 

[Guidance if needed](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)

**Comment by jkulesza** [comment]
Thanks for the suggestion.  Done!
